autoBatWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('populateDB.urls', namespace='populateDB')),
    path('admin/', admin.site.urls),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

populateDB/urls.py
from django.urls import path
from . import views
from django.conf.urls import url
from django.contrib.auth.views import (LoginView, LogoutView, PasswordChangeView, PasswordChangeDoneView)
from django.urls import reverse_lazy

app_name = 'populateDB'

urlpatterns = [
    path('add_user/', views.add_user, name='add_user'),
    path('edit_user/', views.edit_user, name='edit_user'),
    path('home/', views.home, name='home'),
    path('', LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', LogoutView.as_view(template_name='users/logged_out.html'), name='logout'),
    path('password-change/', PasswordChangeView.as_view(success_url=reverse_lazy('populateDB:password_change_done'), template_name='users/password_change_form.html'), name='password_change'),
    path('password_change/done/', PasswordChangeDoneView.as_view(template_name='users/password_change_done.html'),name='password_change_done'),    
    path('add_experiment/', views.add_experiment, name='add_experiment'),
    path('show_experiment', views.show_experiment, name='show_experiment'),
    path('add_experimenter/', views.add_experimenter, name='add_experimenter'),
    path('show_experimenter', views.show_experimenter, name='show_experimenter'),
    path('add_institute/', views.add_institute, name='add_institute'),
    path('show_institute', views.show_institute, name='show_institute'),
    path('add_department/', views.add_department, name='add_department'),
    path('show_department/', views.show_department, name='show_department'),
    path('add_device/', views.add_device, name='add_device'),
    path('show_device/', views.show_device, name='show_device'),
    path('add_donor/', views.add_donor, name='add_donor'),
    path('show_donor/', views.show_donor, name='show_donor'),
    path('add_panel/', views.add_panel, name='add_panel'),
    path('show_panel', views.show_panel, name='show_panel'),

    path('show_experimentfile/', views.show_experimentfile, name='show_experimentfile'),
    path('add_experimentfile/', views.experimentfile.as_view(), name='add_experimentfile'),
    path('show_experimentfile/show_metadata/<int:file_id>', views.show_metadata, name='show_metadata'),
    path('show_experimentfile/show_rawdata/<int:file_id>', views.show_rawMeanData, name='show_rawdata'),
    path('add_experimentfile/update_files/<analysis_id>', views.update_files, name='update_files'),
    path('add_experimentfile/update_files/add_channels/<analysis_id>', views.add_channels, name='add_channels'),
    path('add_experimentfile/update_files/add_channels/analysis_type/<analysis_id>', views.analysis_type, name='analysis_type'),
    path('add_experimentfile/update_files/add_channels/analysis_type/marker_settings_autobat/<analysis_id>', views.marker_settings_autobat, name='marker_settings_autobat'),
    path('add_experimentfile/update_files/add_channels/analysis_type/marker_settings_autograt/<analysis_id>', views.marker_settings_autograt, name='marker_settings_autograt'),
    path('add_experimentfile/update_files/add_channels/analysis_type/marker_settings_CD32autobat/<analysis_id>', views.marker_settings_CD32autobat, name='marker_settings_CD32autobat'),

    path('add_experimentfile/update_files/add_channels/analysis_type/marker_settings_autobat/run_analysis_autobat/<analysis_id>', views.run_analysis_autobat, name='run_analysis_autobat'),
    path('add_experimentfile/update_files/add_channels/analysis_type/marker_settings_autograt/run_analysis_autograt/<analysis_id>', views.run_analysis_autograt, name='run_analysis_autograt'),
    path('add_experimentfile/update_files/add_channels/analysis_type/marker_settings_CD32autobat/run_analysis_CD32autobat/<analysis_id>', views.run_analysis_CD32autobat, name='run_analysis_CD32autobat'),

    path('analysis/', views.show_analysis, name='show_analysis'),
    path('analysis/list_files/<analysis_id>', views.list_files, name='list_files'),

    path('analysis/delete_alert/<analysisMarker_id>', views.delete_analysis_alert, name='delete_alert'),
    path('analysis/delete_alert/delete_analysis/<analysisMarker_id>', views.delete_analysis, name='delete_analysis'),
    path('analysis/show_channels/<analysis_id>', views.show_channels, name='show_channels'),
    path('analysis/list_thresholds/<analysisMarker_id>', views.list_thresholds, name='list_thresholds'),
    path('analysis/download_pdf/<analysisMarker_id>', views.download_pdf, name='download_pdf'),
    path('analysis/download_xlsx/<analysisMarker_id>', views.download_xlsx, name='download_xlsx'),
    path('analysis_report/', views.analysis_report, name='analysis_report'),
    path('analysis_report/show_channels/<analysis_id>', views.show_channels, name='show_channels'),
    path('analysis_report/view_plots/<result_id>', views.view_plots, name='view_plots'),
    path('analysis_report/view_plots/update_plots_symbol/<analysisMarker_id>', views.update_plots_symbol, name='update_plots_symbol'),
    path('analysis/re_analysis_alert', views.re_analysis_alert, name='re_analysis_alert'),
    path('analysis/run_re_analysis_all', views.run_re_analysis_all, name='run_re_analysis_all'),

    path('analysis/re_analysis_all', views.re_analysis_all, name='re_analysis_all'),
    path('analysis/results_to_CSV', views.results_to_CSV, name='results_to_CSV'),
    path('analysis/thresholds_to_CSV', views.thresholds_to_CSV, name='thresholds_to_CSV'),
    path('thresholds_report/', views.thresholds_report, name='thresholds_report'),
    path('analysis/analysis_error/<analysisMarker_id>', views.analysis_error, name='analysis_error'),
    path('analysis/analysis_info/<analysisMarker_id>', views.analysis_info, name='analysis_info'),
    path('research_questions/', views.research_questions, name='research_questions'),
    path('research_results/', views.research_results, name='research_results'),
    #path('results/', views.ListResults.as_view(), name = 'list_results'),
    path('ajax/bat_names', views.getBat_names, name = "getBat_names"),
    path('ajax/file_controls', views.getFile_controls, name = "getFile_controls"),
    path('ajax/panel_names', views.getPanel_names, name = "getPanel_names"),
    path('ajax/analysis_type', views.getAnalysis_type, name = "getAnalysis_type"),
    path('ajax/clinical_classes', views.getClinical_classes, name = "getClinical_classes"),
    path('ajax/responders', views.getResponders, name = "getResponders"),
    path('ajax/allergens', views.get_allergens, name = "get_allergens"),
    path('research_results/downloadResults_pdf/<files_ids>', views.downloadResults_pdf, name='downloadResults_pdf'),
    path('research_results/downloadResults_xlsx/<excel_name>', views.downloadResults_xlsx, name='downloadResults_xlsx'),
    path('research_results/show_channels/<analysis_id>', views.show_channels, name='show_channels'),
    path('files_data_CSV', views.files_data_CSV, name='files_data_CSV'),
    path('blood_tests/', views.blood_tests, name='blood_tests'),
    path('skin_tests/', views.skin_tests, name='skin_tests'),
    path('ofc_tests/', views.ofc_tests, name='ofc_tests'),
    ]

populateDB/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from . import forms
from . import models
from django.views.generic import View
from django.http import HttpResponse, Http404
import sys
import os
from django.forms import formset_factory
from django.core.files.storage import FileSystemStorage
from django.db.models import Q, Case, When, Value, Count, Avg, Sum
from datetime import date
import config
sys.path.insert(0, os.path.join(config.AUTOBAT_PATH, 'autoBat'))
from django.conf import settings
from Data import Data
from .functions import change_FCS_data, create_path, image_grid, pdf_grid, add_symbol
from .tasks import run_analysis_cd32autobat_task, run_analysis_autobat_task, run_analysis_autograt_task, proccess_files, save_pdf
from djqscsv import render_to_csv_response
from .serializers import ResultsSerializers
from .pagination import StandardResultsSetPagination
from rest_framework.generics import ListAPIView
from django.http import JsonResponse
import pandas as pd
import time
import shutil
from django.db.models import F
import re
import csv
from django.views.decorators.clickjacking import xframe_options_deny
from django.views.decorators.clickjacking import xframe_options_sameorigin

bat_version='1.0.4'
#'1.0.2'
grat_version='1.0.4'
#'1.0.1'
cd32bat_version='1.0.0'


@login_required
def home(request):
    num_bats = models.Experiment.objects.all().count()
    num_donors = models.Donor.objects.all().count()
    num_files = models.ExperimentFiles.objects.all().count()
    num_analysis = models.AnalysisMarkers.objects.all().count()
    context = {
        "welcome": "Welcome to The Auto-Bat Web",
        'num_bats': num_bats,
        'num_donors': num_donors,
        'num_files': num_files,
        'num_analysis': num_analysis
    }
    return render(request, 'home.html', context=context)

@login_required
def add_user(request):
    if request.method == 'POST':
        form = forms.AddUserForm(request.POST or None)
        if form.is_valid():
            new_user = form.save(commit=False)
            new_user.set_password(
                form.cleaned_data.get('password')
            )
            new_user.save()
            return render(request, 'users/add_user_done.html')
    else:
        form = forms.AddUserForm()

    context = {
        "form": form
    }
    return render(request, 'users/add_user.html', context=context)


@login_required
def edit_user(request):
    if request.method == 'POST':
        user_form = forms.EditUserForm(instance=request.user,
                                 data=request.POST)
        if user_form.is_valid():
            user_form.save()
            return render(request, 'users/edit_user_done.html')
    else:
        user_form = forms.EditUserForm(instance=request.user)
    context = {
        'form': user_form,
    }
    return render(request, 'users/edit_user.html', context=context)

@login_required
def add_experiment(request):
    if request.method == 'POST':
        form = forms.ExperimentForm(request.POST or None)
        if form.is_valid():
            new_experiment = form.save(commit=False)
            new_experiment.save()
            experiment_data = models.Experiment.objects.all().order_by('bat_id').reverse()
            return render(request,"expermiments/show_experiment.html",{'experiment_data':experiment_data})
    else:
        form = forms.ExperimentForm()
    context = {
        "form": form
    }
    
    return render(request, 'expermiments/add_experiment.html', context=context)

@login_required
def show_experiment(request):  
    experiment_data = models.Experiment.objects.all().order_by('bat_id').reverse()
    return render(request,"expermiments/show_experiment.html",{'experiment_data':experiment_data})  

@login_required
def add_institute(request):
    institutes_data = models.Institutes.objects.all().order_by('institute_id').reverse()
    if request.method == 'POST':
        form = forms.InstitutesForm(request.POST or None)
        if form.is_valid():
            new_institute = form.save(commit=False)
            new_institute.save()            
            return render(request,"institutes/show_institutes.html",{'institutes_data':institutes_data}) 
    else:
        form = forms.InstitutesForm()

    context = {
        "form": form
    }

    return render(request, 'institutes/add_institutes.html', context=context)

@login_required
def show_institute(request):  
    institutes_data = models.Institutes.objects.all().order_by('institute_id').reverse()
    return render(request,"institutes/show_institutes.html",{'institutes_data':institutes_data}) 



@login_required
def add_panel(request):
    panels_data = models.Panels.objects.all().order_by('panel_id').reverse()
    if request.method == 'POST':
        form = forms.PanelsForm(request.POST or None)
        if form.is_valid():
            new_panel = form.save(commit=False)
            new_panel.save()
            return render(request,"panels/show_panels.html",{'panels_data':panels_data}) 
    else:
        form = forms.PanelsForm()

    context = {
        "form": form
    }

    return render(request, 'panels/add_panels.html', context=context)

@login_required
def show_panel(request):  
    panels_data = models.Panels.objects.all().order_by('panel_id').reverse()
    return render(request,"panels/show_panels.html",{'panels_data':panels_data}) 


@login_required
def add_department(request):
    departments_data = models.Departments.objects.all().order_by('department_id').reverse()
    if request.method == 'POST':
        form = forms.DepartmentsForm(request.POST or None)
        if form.is_valid():
            new_experiment = form.save(commit=False)
            new_experiment.save()
            return render(request,"departments/show_departments.html",{'departments_data':departments_data}) 
    else:
        form = forms.DepartmentsForm()
    context = {
        "form": form
    }
    return render(request, 'departments/add_departments.html', context=context)

@login_required
def show_department(request):  
    departments_data = models.Departments.objects.all().order_by('department_id').reverse()
    return render(request,"departments/show_departments.html",{'departments_data':departments_data}) 

@login_required
def add_experimenter(request):
    experimenters_data = models.Experimenters.objects.all().order_by('experimenter_id').reverse()
    if request.method == 'POST':
        form = forms.ExperimentersForm(request.POST or None)
        if form.is_valid():
            new_experimenter = form.save(commit=False)
            new_experimenter.save()
            return render(request,"experimenters/show_experimenters.html",{'experimenters_data':experimenters_data})
    else:
        form = forms.ExperimentersForm()

    context = {
        "form": form
    }
    return render(request, 'experimenters/add_experimenters.html', context=context)

@login_required
def show_experimenter(request):  
    experimenters_data = models.Experimenters.objects.all().order_by('experimenter_id').reverse()
    return render(request,"experimenters/show_experimenters.html",{'experimenters_data':experimenters_data})

@login_required
def add_device(request):
    devices_data = models.Devices.objects.all().order_by('device_id').reverse()
    if request.method == 'POST':
        form = forms.DevicesForm(request.POST or None)
        if form.is_valid():
            new_device = form.save(commit=False)
            new_device.save()
            return render(request,"devices/show_devices.html",{'devices_data':devices_data})
    else:
        form = forms.DevicesForm()

    context = {
        "form": form
    }
    return render(request, 'devices/add_devices.html', context=context)

@login_required
def show_device(request):  
    devices_data = models.Devices.objects.all().order_by('device_id').reverse()
    return render(request,"devices/show_devices.html",{'devices_data':devices_data})

@login_required
def add_donor(request):
    donors_data= models.Donor.objects.all().order_by('donor_id').reverse()
    if request.method == 'POST':
        form = forms.DonorForm(request.POST or None)
        if form.is_valid():
            new_donor = form.save(commit=False)
            new_donor.save()
            return render(request,"donors/show_donors.html",{'donors_data':donors_data})
    else:
        form = forms.DonorForm()

    context = {
        "form": form
    }
    return render(request, 'donors/add_donors.html', context=context)

@login_required
def show_donor(request):  
    donors_data= models.Donor.objects.all().order_by('donor_id').reverse()
    return render(request,"donors/show_donors.html",{'donors_data':donors_data})

class experimentfile(View):
    def get(self, request):
        form = forms.ExperimentFilesForm()
        return render(request, 'files/add_files.html', context={'form':form})

    def post(self, request):
        if request.method=='POST':
            form = forms.ExperimentFilesForm(request.POST, request.FILES)
            files = request.FILES.getlist('file')
            if form.is_valid():
                bat_id = form.cleaned_data['bat_id']
                donor_id = form.cleaned_data['donor_id']
                panel_id = form.cleaned_data['panel_id']
                condition = form.cleaned_data['condition']
                condition = condition.replace(" ", "_")
                analysis_instance = models.Analysis(bat_id=bat_id, donor_id=donor_id, panel_id=panel_id, condition=condition)
                analysis_instance.user_id = request.user.id
                analysis_instance.save()
                analysis_id = analysis_instance.analysis_id
                if condition:
                    files_dir = os.path.join(settings.MEDIA_ROOT, f"FCS_files/{bat_id}/{donor_id}/{panel_id}/{condition}")
                else:
                    files_dir = os.path.join(settings.MEDIA_ROOT, f"FCS_files/{bat_id}/{donor_id}/{panel_id}")

populateDB/templates/expermiments/add_experiment.html
{% include "base.html" %}
{% include "navbar.html" %}
<br>
<br>
<br>
{% if form.errors %}
    
{% endif %}

<div class="container-fluid vh-100">
    <div class="" style="margin-top:50px">
        <div class="rounded d-flex justify-content-center">
            <div class="col-md-5 col-sm-12 shadow-lg p-5 bg-light">
                <div class="text-center">
                    <h3 class="text-primary">Add Experiment</h3>
                    <div class="modal-footer"></div>              </div>
                    <form method="POST" class="post-form" action="" autocomplete="off">
                      {% csrf_token %}  
                      <div class="container">  
                        <br>  
                        <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Bat Name:</label>  
                          <div class="col-sm-4">  
                            {{ form.bat_name }}  
                          </div>  
                        </div>  
                        <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Date of Experiment:</label>  
                          <div class="col-sm-4">  
                            {{ form.date_of_measurement }}  
                          </div>  
                        </div>  
                          <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Institute:</label>  
                          <div class="col-sm-4">  
                            {{ form.institute_id }}  
                          </div>  
                        </div>  
                          <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Experimenter:</label>  
                          <div class="col-sm-4">  
                            {{ form.experimenter_id }}  
                          </div>  
                        </div>
                        <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Device:</label>  
                          <div class="col-sm-4">  
                            {{ form.device_id }}  
                          </div>  
                        </div>  
                          <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Bead Experiment:</label>  
                          <div class="col-sm-4">  
                            {{ form.beadExperiment }}  
                          </div>  
                        </div>
                        <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Special Experiment:</label>  
                          <div class="col-sm-4">  
                            {{ form.specialExperiment }}  
                          </div>  
                        </div>  
                          <div class="form-group row">  
                          <label class="col-sm-4 col-form-label">Special Notes:</label>  
                          <div class="col-sm-4">  
                            {{ form.specialNotes }}  
                          </div>  
                        </div> 
                      </div>
                      <div class="form-group row">  
                        <label class="col-sm-1 col-form-label"></label>  
                        <div class="modal-footer"></div>
                        <button type="submit" class="btn btn-primary">Save</button>  
                        </div>  
                      </div>  
                        </div>  
                    </form>  
                </div>
            </div>
        </div>
    </div>
</div>

populateDB/templates/expermiments/show_experiment.html
{% include "base.html" %}
{% include "navbar.html" %}

<br></br>
<div class="container">

  <center><h1>Experiments</h1></center>
  <br></br>
 <a href="{% url 'populateDB:add_experiment' %}" class="btn btn-primary">New Experiment</a> 
 <br></br>
   <table id="analysis-table" class="display" style="width:100%">
    <thead >  
        <tr>  
            <th>Bat Name</th>
            <th>Date of Experiment</th>  
            <th>Institute</th>  
            <th>Experimenter</th>  
            <th>Device</th>  
            <th>Bead Experiment</th>
            <th>Special Experiment</th>
	    <th>Special Notes</th>
    
        </tr>  
        </thead>  
        <tbody>  
    {% for experiment in experiment_data %}  
        <tr>  
            <td>{{ experiment.bat_name }}</td>  
            <td>{{ experiment.date_of_measurement }}</td>  
            <td>{{ experiment.institute_id }}</td>  
            <td>{{ experiment.experimenter_id }}</td>
            <td>{{ experiment.device_id }}</td>  
            <td>{{ experiment.beadExperiment }}</td>
            <td>{{ experiment.specialExperiment }}</td>
	     <td>{{ experiment.specialNotes }}</td>
    
        </tr> 
    {% empty %}
    <tr>
      <td colspan="7" class="text-center bg-warning">No Data</td>
    </tr>
  {% endfor %}

   </tbody>
   </table>
</div>

<script>
	  $(document).ready(function(){
			                    $('table.display').DataTable({
							                                      /* Disable initial sort */
							                                              "aaSorting": []
							                                  });
		  })
</script>